/** code generated by Kinyoshi */
package net.minecraft.src;

import java.io.*;
import java.util.*;
import net.minecraft.client.Minecraft;

public class mod_DeadBushDos extends BaseMod
{
	public mod_DeadBushDos()
	{
		readWriteProperties();

        BlockDeadBushDos = (new BlockDeadBushDos(BlockDeadBushDosID)).setHardness(0.0F).setResistance(0.0F).setLightValue(0.0F).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("deadbush");
        ModLoader.addName(BlockDeadBushDos, "Dead Bush");
    }

	public void readWriteProperties() {
		Properties properties = new Properties();
		try
		{
            File file = new File((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/DeadBushDos.config").toString());
            boolean flag = file.createNewFile();
            if(flag)
            {
                FileOutputStream fileoutputstream = new FileOutputStream(file);
                properties.setProperty("BlockDeadBushDosID", Integer.toString(239));
                properties.setProperty("ShouldMoreSpawn", Boolean.toString(false));
                properties.store(fileoutputstream, "Change the ID's to fix ID incompatibilities.");
                fileoutputstream.close();
            }
            properties.load(new FileInputStream((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/DeadBushDos.config").toString()));
            BlockDeadBushDosID = Integer.parseInt(properties.getProperty("BlockDeadBushDosID"));
            ShouldMoreSpawn = Boolean.parseBoolean(properties.getProperty("ShouldMoreSpawn"));
        }
        catch(IOException ioexception)
        {
            ioexception.printStackTrace();
            BlockDeadBushDosID = 239;
            ShouldMoreSpawn = false;
        }
	}
	
	public String getVersion() {
		return "MineCraft1.5.2__mod_DeadBushDos1.5.2r1";
	}

	public int addFuel(int par1, int par2)
    {
        if(par1 == BlockDeadBushDos.blockID)
        {
            return 100;
        }
        if(par1 == Block.deadBush.blockID)
        {
            return 100;
        }
        return 0;
    }

    public void generateSurface(World world, Random r, int i, int j)
 {
 	if (ShouldMoreSpawn == true)
	{
    for(int k = 0; k < 35 + r.nextInt(50); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         (new WorldGenDeadBushDos()).generate(world, r, randPosX, randPosY, randPosZ);
    }
    
    for(int k = 0; k < 35 + r.nextInt(50); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         (new WorldGenDeadBushDos()).generate(world, r, randPosX, randPosY, randPosZ);
    }
	}
	else
	{
    for(int k = 0; k < 20 + r.nextInt(30); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         (new WorldGenDeadBushDos()).generate(world, r, randPosX, randPosY, randPosZ);
    }
    
    for(int k = 0; k < 20 + r.nextInt(30); k++)
    {
         int randPosX = i + r.nextInt(16);
         int randPosY = r.nextInt(256);
         int randPosZ = j + r.nextInt(16);
         (new WorldGenDeadBushDos()).generate(world, r, randPosX, randPosY, randPosZ);
    }
	}
 }
          
    public static Block BlockDeadBushDos;
    public static int BlockDeadBushDosID;
    public static boolean ShouldMoreSpawn;

	public void load()
	{
		ModLoader.registerBlock(BlockDeadBushDos);
	}
}
